version: '3'
services:
    db:
        image: postgres:12.4
        environment:
          - POSTGRES_PASSWORD=rush
        volumes:
          - ${PWD}/init:/docker-entrypoint-initdb.d
        ports:
          - "5432:5432"
